const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_17_39_10_13_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTUyLFxuICAgICAgICAyNixcbiAgICAgICAgMTk0LFxuICAgICAgICAxNTEsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTM0LFxuICAgICAgICAyNixcbiAgICAgICAgNDUsXG4gICAgICAgIDQ0LFxuICAgICAgICAyMjAsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTEwLFxuICAgICAgICAxNjgsXG4gICAgICAgIDM3LFxuICAgICAgICAxNTEsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTIsXG4gICAgICAgIDIwMixcbiAgICAgICAgMjMyLFxuICAgICAgICAxMzksXG4gICAgICAgIDUsXG4gICAgICAgIDEzNSxcbiAgICAgICAgOTUsXG4gICAgICAgIDEzLFxuICAgICAgICAxNSxcbiAgICAgICAgMTQwLFxuICAgICAgICAxMjIsXG4gICAgICAgIDk4LFxuICAgICAgICAxMjMsXG4gICAgICAgIDg4LFxuICAgICAgICAxMjAsXG4gICAgICAgIDEyN1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMDEsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTA2LFxuICAgICAgICAyNTIsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTAwLFxuICAgICAgICAxNDcsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTcsXG4gICAgICAgIDUxLFxuICAgICAgICAxMDgsXG4gICAgICAgIDk4LFxuICAgICAgICA0MyxcbiAgICAgICAgMTcyLFxuICAgICAgICA2MCxcbiAgICAgICAgODYsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTMsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMTMsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTUxLFxuICAgICAgICA4NyxcbiAgICAgICAgMzUsXG4gICAgICAgIDEyMixcbiAgICAgICAgMjUzLFxuICAgICAgICA0MCxcbiAgICAgICAgMTQ1LFxuICAgICAgICAyNDMsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTYxLFxuICAgICAgICA1M1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODgsXG4gICAgICAgIDI3LFxuICAgICAgICAxNzcsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTcyLFxuICAgICAgICAxMDEsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMjI3LFxuICAgICAgICAxNzUsXG4gICAgICAgIDExNyxcbiAgICAgICAgMjAxLFxuICAgICAgICAxNixcbiAgICAgICAgMjE1LFxuICAgICAgICAxNTAsXG4gICAgICAgIDQxLFxuICAgICAgICAyMTcsXG4gICAgICAgIDIyNyxcbiAgICAgICAgOTMsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMjI2LFxuICAgICAgICAzNixcbiAgICAgICAgMTUyLFxuICAgICAgICA3OSxcbiAgICAgICAgMjQ5LFxuICAgICAgICAyOSxcbiAgICAgICAgMTIsXG4gICAgICAgIDEyNyxcbiAgICAgICAgNzQsXG4gICAgICAgIDE2NSxcbiAgICAgICAgNDEsXG4gICAgICAgIDE4NyxcbiAgICAgICAgNjVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOCxcbiAgICAgICAgOTMsXG4gICAgICAgIDIwNCxcbiAgICAgICAgNTMsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMTUsXG4gICAgICAgIDIwNixcbiAgICAgICAgMzMsXG4gICAgICAgIDIzMixcbiAgICAgICAgNjgsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMzMsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMzUsXG4gICAgICAgIDI4LFxuICAgICAgICAyMjgsXG4gICAgICAgIDEzMyxcbiAgICAgICAgODksXG4gICAgICAgIDI1MyxcbiAgICAgICAgMjUsXG4gICAgICAgIDE0MCxcbiAgICAgICAgNixcbiAgICAgICAgMTc0LFxuICAgICAgICA0OCxcbiAgICAgICAgMCxcbiAgICAgICAgMTE4LFxuICAgICAgICAxNjcsXG4gICAgICAgIDE2NixcbiAgICAgICAgMzcsXG4gICAgICAgIDk3LFxuICAgICAgICAxOTcsXG4gICAgICAgIDg2XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4OCxcbiAgICAgICAgMTM3LFxuICAgICAgICA2OCxcbiAgICAgICAgMjUsXG4gICAgICAgIDgyLFxuICAgICAgICAxOTksXG4gICAgICAgIDEyNyxcbiAgICAgICAgMTQsXG4gICAgICAgIDEzMCxcbiAgICAgICAgNzIsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTgsXG4gICAgICAgIDg2LFxuICAgICAgICAxMDMsXG4gICAgICAgIDI1MCxcbiAgICAgICAgOSxcbiAgICAgICAgMjIxLFxuICAgICAgICAyMDMsXG4gICAgICAgIDgwLFxuICAgICAgICA2MixcbiAgICAgICAgOTIsXG4gICAgICAgIDYzLFxuICAgICAgICAxNTEsXG4gICAgICAgIDE4NyxcbiAgICAgICAgNDAsXG4gICAgICAgIDE5NCxcbiAgICAgICAgOTIsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjE0LFxuICAgICAgICAyMTIsXG4gICAgICAgIDEyNixcbiAgICAgICAgODBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTEzLFxuICAgICAgICAxNTAsXG4gICAgICAgIDExMCxcbiAgICAgICAgMjAyLFxuICAgICAgICAyOSxcbiAgICAgICAgMTk2LFxuICAgICAgICAxNTAsXG4gICAgICAgIDU5LFxuICAgICAgICAyNTQsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMzgsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTgzLFxuICAgICAgICA4NCxcbiAgICAgICAgMTI3LFxuICAgICAgICAyMDUsXG4gICAgICAgIDI2LFxuICAgICAgICAxOTUsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMjAzLFxuICAgICAgICA0OSxcbiAgICAgICAgMTkyLFxuICAgICAgICAyMzcsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTYzLFxuICAgICAgICAxODgsXG4gICAgICAgIDQyLFxuICAgICAgICA2OSxcbiAgICAgICAgNzksXG4gICAgICAgIDYxLFxuICAgICAgICAyNDEsXG4gICAgICAgIDcwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDI0OCxcbiAgICAgICAgICAyMSxcbiAgICAgICAgICA1LFxuICAgICAgICAgIDgyLFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICA5OCxcbiAgICAgICAgICA4NyxcbiAgICAgICAgICAzMyxcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgMzAsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDI1NSxcbiAgICAgICAgICAxNzIsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgNTcsXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDgzLFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICA2MCxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICA4NixcbiAgICAgICAgICA2OVxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA2NixcbiAgICAgICAgICAxNjksXG4gICAgICAgICAgODcsXG4gICAgICAgICAgNjAsXG4gICAgICAgICAgMTE3LFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDIyNyxcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMTI5LFxuICAgICAgICAgIDkzLFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICAyMDIsXG4gICAgICAgICAgMjM2LFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICAyLFxuICAgICAgICAgIDI0MSxcbiAgICAgICAgICA3MyxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgNjcsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgMTM5LFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgMjIxLFxuICAgICAgICAgIDU5LFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgMTJcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4NSxcbiAgICAgICAgOTIsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMjQzLFxuICAgICAgICA2MSxcbiAgICAgICAgMjQ3LFxuICAgICAgICA2MixcbiAgICAgICAgMTY2LFxuICAgICAgICAyMDgsXG4gICAgICAgIDE4LFxuICAgICAgICAxMjcsXG4gICAgICAgIDE4NCxcbiAgICAgICAgNyxcbiAgICAgICAgMTc4LFxuICAgICAgICAxOTQsXG4gICAgICAgIDQyLFxuICAgICAgICAyMzEsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMjM2LFxuICAgICAgICAxNzEsXG4gICAgICAgIDE2OSxcbiAgICAgICAgNzYsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMTg0LFxuICAgICAgICA3NSxcbiAgICAgICAgMzgsXG4gICAgICAgIDExLFxuICAgICAgICAxNjMsXG4gICAgICAgIDE4LFxuICAgICAgICA5MCxcbiAgICAgICAgMjQwLFxuICAgICAgICA0NyxcbiAgICAgICAgNDQsXG4gICAgICAgIDEsXG4gICAgICAgIDYsXG4gICAgICAgIDcsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTQzLFxuICAgICAgICAyNyxcbiAgICAgICAgMjIwLFxuICAgICAgICAyMTIsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTg4LFxuICAgICAgICAxNzgsXG4gICAgICAgIDk3LFxuICAgICAgICAxMTEsXG4gICAgICAgIDExLFxuICAgICAgICAxMzAsXG4gICAgICAgIDQzLFxuICAgICAgICA2NCxcbiAgICAgICAgMTI1LFxuICAgICAgICAxOSxcbiAgICAgICAgMTU3LFxuICAgICAgICAxNDMsXG4gICAgICAgIDIwNixcbiAgICAgICAgMjQ0LFxuICAgICAgICAzNixcbiAgICAgICAgMTMwLFxuICAgICAgICAyNDIsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMjM2LFxuICAgICAgICAyMzgsXG4gICAgICAgIDE0LFxuICAgICAgICAxMjlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDEzMCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJYNW5xMGlJZ0FZQmdKNnRLWVkrSkNLeVh3SmF6bmpyUzh0TXJRRUF5bXZnPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjI1NDc4ODQxMDI4OUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiQkJEQ0U5QjVEM0NDODJDNUFBMjk2RDE0N0QyNEM0MTNcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI4ODQxMTkxXG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjU0Nzg4NDEwMjg5QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI1NkRFNzhFRTQ3QTA1NTVCMDUzMkJDNDRGRUFEN0MyOVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3Mjg4NDExOTNcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyNTQ3ODg0MTAyODlAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjlDRTMzQjdGMEE2NDc5MTkyQkFFQzU3MDFENDhFQUYwXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyODg0MTE5N1xuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJBUDUtcXY4RlEyZXVpd3ZTdWlUSzlRXCIsXG4gIFwicGhvbmVJZFwiOiBcImU5NTBmYzI3LWVlY2YtNDZmYi1iMTRiLTQ4MjhlN2FhNjYxM1wiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxOTMsXG4gICAgICA3NyxcbiAgICAgIDE1OSxcbiAgICAgIDY1LFxuICAgICAgODAsXG4gICAgICA5MCxcbiAgICAgIDM1LFxuICAgICAgNTksXG4gICAgICA0NCxcbiAgICAgIDksXG4gICAgICAyMzEsXG4gICAgICAyNyxcbiAgICAgIDE3MixcbiAgICAgIDQ0LFxuICAgICAgMjA4LFxuICAgICAgMTY0LFxuICAgICAgMTkxLFxuICAgICAgMjI1LFxuICAgICAgMjEsXG4gICAgICAyNTNcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTUsXG4gICAgICAyMDAsXG4gICAgICAxMTEsXG4gICAgICA1MCxcbiAgICAgIDEyMixcbiAgICAgIDExNSxcbiAgICAgIDE5NCxcbiAgICAgIDIzMCxcbiAgICAgIDIxMixcbiAgICAgIDE1OCxcbiAgICAgIDQwLFxuICAgICAgMTk3LFxuICAgICAgMTU5LFxuICAgICAgMzYsXG4gICAgICAxNCxcbiAgICAgIDIwMixcbiAgICAgIDE4MixcbiAgICAgIDE1OCxcbiAgICAgIDIzLFxuICAgICAgMTEwXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIlZLVkI0SjNDXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyNTQ3ODg0MTAyODk6MkBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcImNvbGxvXCIsXG4gICAgXCJsaWRcIjogXCIxMjQ0NjAwNjU2MzI1MDc6MkBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNJejNrUEVHRU9HTHNMZ0dHQUlnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIkN2b3VsOGZnOUtheFlPZzRtNzBZYlJwRVprK1BGd3l2cHJ1T2Q2aVJ2RUk9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwibHYxb0Q5VXFBTENYOVhTU0Y3eS8ycG9HajlGVkNrNU9jaUUyNnpwNHZGY2wxdkJrYUUydHNmSE1pY0RwY0NuYlFnVW1IZms0U3VqU09LRGl6aFV4QlE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwicmluYkg5dTRrT0JnMFlmZDdXTjdDbHhMbEI5UlIxNjVLaWRpS1RpV3lnS3U5QVdSdFRIOFlOSVlYOFhaMEN6TCtQSkFEaXBseUh2aWxyZU1iMVFjaVE9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjU0Nzg4NDEwMjg5OjJAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAyNTAsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDE5OSxcbiAgICAgICAgICAyMjQsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICAxODksXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDY4LFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgMjMsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDExOSxcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgMTQ1LFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICA2NlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI4ODQxMTkwLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBQ0RPXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFDRE8uanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJpTG1aNVNIUFBjWkpRRTZmdE1KT0dxUmJRNFFVR1lLenVvK1R1emU3dUdBPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE4NDc4NjgzMDAsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyODgzODk3NDc4N1wifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
